definitions:
  controllers.ReqNewUser:
    properties:
      email:
        type: string
      mobile:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - mobile
    - password
    - username
    type: object
  controllers.ReqUpdateUser:
    properties:
      email:
        type: string
      mobile:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - mobile
    - password
    - username
    type: object
  models.User:
    properties:
      createdat:
        type: string
      createdby:
        type: string
      email:
        type: string
      id:
        type: string
      mobile:
        type: string
      password:
        type: string
      updatedat:
        type: string
      updatedby:
        type: string
      username:
        type: string
    type: object
  utils.Message:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /ping:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Message'
      summary: ping example
      tags:
      - ping
  /user:
    delete:
      consumes:
      - application/json
      description: delete a single user
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: User deleted successfully
          schema:
            $ref: '#/definitions/utils.Message'
      summary: delete a single user
      tags:
      - user delete
    get:
      consumes:
      - application/json
      description: get a single user
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: get a single user
      tags:
      - user getusers
    post:
      consumes:
      - application/json
      description: create a single user
      parameters:
      - description: New User
        in: body
        name: ReqNewUser
        required: true
        schema:
          $ref: '#/definitions/controllers.ReqNewUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: create user
      tags:
      - user create post
    put:
      consumes:
      - application/json
      description: create a single user
      parameters:
      - description: Update User
        in: body
        name: ReqUpdateUser
        required: true
        schema:
          $ref: '#/definitions/controllers.ReqUpdateUser'
      produces:
      - application/json
      responses:
        "200":
          description: User updated successfully
          schema:
            $ref: '#/definitions/utils.Message'
      summary: create user
      tags:
      - user create post
  /users:
    get:
      consumes:
      - application/json
      description: get all users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: get all users
      tags:
      - user getusers
swagger: "2.0"
